basic.forever(function () {
    basic.showIcon(IconNames.Happy)
    basic.pause(500)
    basic.showIcon(IconNames.Asleep)
    basic.pause(500)
    basic.showIcon(IconNames.Sad)
    basic.pause(500)
    basic.showIcon(IconNames.Confused)
    basic.pause(500)
})
